"""Lists s3://lidalps3d/buildings/ (see scripts/buildings.py) and writes the
"x.y" cells with a built .city.jsonl as a static JS module, replacing the
runtime-fetched bom_buildings.txt overlays.js used to load.
"""

import json
import subprocess
from pathlib import Path

S3_ENDPOINT = "https://s3.sbg.io.cloud.ovh.net"
S3_BUCKET = "lidalps3d"
S3_PREFIX = "buildings/"

OUT_PATH = (
    Path(__file__).resolve().parents[5] / "webapp" / "src" / "buildingsBom.js"
)


def list_stems():
    stems = []
    token = None
    while True:
        cmd = [
            "aws",
            "s3api",
            "list-objects-v2",
            "--bucket",
            S3_BUCKET,
            "--prefix",
            S3_PREFIX,
            "--endpoint-url",
            S3_ENDPOINT,
        ]
        if token:
            cmd += ["--starting-token", token]
        out = json.loads(
            subprocess.run(cmd, capture_output=True, text=True, check=True).stdout
        )
        for obj in out.get("Contents", []):
            name = Path(obj["Key"]).name
            if name.endswith(".city.jsonl"):
                stems.append(name[: -len(".city.jsonl")])
        token = out.get("NextContinuationToken")
        if not token:
            break
    return stems


def stem_to_cell(stem):
    parts = stem.split("_")
    x0, y0plus1 = int(parts[2]), int(parts[3])
    return f"{x0}.{y0plus1 - 1}"


def main():
    cells = sorted({stem_to_cell(s) for s in list_stems()})
    body = ",\n".join(f'  "{c}"' for c in cells)
    OUT_PATH.write_text(
        '// Generated by "python -m alpineview_builder.scripts.build_buildings_bom".\n'
        '// "x.y" per L93 km cell with a built .city.jsonl (see scripts/buildings.py).\n'
        "export const BUILDINGS_BOM = new Set([\n"
        f"{body}\n"
        "]);\n"
    )
    print(len(cells), "cell(s) ->", OUT_PATH)


if __name__ == "__main__":
    main()
