export const ALPINIST_QUOTES = [
  { text: "Parce qu'elle est là.", author: "George Mallory" },
  { text: "La montagne n'est ni juste ni injuste. Elle est dangereuse.", author: "Reinhold Messner" },
  { text: "Je grimpe parce que si je n'escalade pas, je tombe.", author: "Alex Honnold" },
  { text: "La montagne est le maître et nous sommes ses élèves.", author: "Reinhold Messner" },
  { text: "L'altitude, c'est la liberté.", author: "Ed Viesturs" },
  { text: "Le sommet n'est que la moitié du voyage.", author: "Edmund Hillary" },
  { text: "Monte ton pied gauche !", author: "Ton assureur" },
  { text: "La montagne est un enseignant silencieux, dont les leçons de modestie, de persévérance et de préparation sont éternelles.", author: "Michael Kennedy" },
  { text: "Les montagnes ne sont pas des stades où je satisfais ma curiosité pour savoir si je peux gravir telle ou telle paroi. Les montagnes sont des lieux où je pratique ma religion.", author: "Anatoli Boukreev" },
  { text: "Lorsque vous vous trouvez en montagne, les règles du jeu changent. Vous faites partie de la montagne. Vous ne la grimpez pas pour y laisser votre marque.", author: "Lou Whittaker" },
  { text: "Ce n'est pas la montagne que nous conquérons, mais nous-mêmes.", author: "Edmund Hillary" },
  { text: "Le sommet est une illusion, mais l'escalade est réelle.", author: "Urs Odermatt" },
  { text: "Les montagnes sont des êtres vivants, des créatures pleines d'âme. Vous ne les domptez pas, vous entrez en relation avec elles.", author: "George Mallory" },
  { text: "Si la montagne semble inaccessible aujourd'hui, escaladez-la demain.", author: "Walter Bonatti" },
  { text: "La montagne est le miroir de l'âme.", author: "Reinhold Messner" },
  { text: "Un programme sans bug c'est comme un refuge sans Génépi.", author: "Le développeur." },
  { text: "L'alpinisme, c'est un art de vivre, un engagement envers soi-même et envers la nature.", author: "Gaston Rébuffat" },
  { text: "L'alpinisme ne consiste pas seulement à conquérir des sommets, mais aussi à découvrir des parties inconnues de soi-même.", author: "Andy Kerr" },
  { text: "La montagne ne triche pas, elle est toujours elle-même.", author: "Reinhold Messner" },
  { text: "Pourtaaaant que la montaaagne est bellleuuuh.", author: "Jean Ferrat" },

];
